### ISSUE TITLE
Quali nazionalità hanno contribuito di più all'immigrazione nel 21° secolo? In quali quartieri l'immigrazione è cresciuta più velocemente? E da quali nazionalità?

### ISSUE THREAD

**Issue by ghost** [spaghetti-open-data/-milano-melting-pot#1]
Ciao a tutti, 

ho iniziato a fare qualche esperimento con i dati 

per adesso mi sono concentrato sul punto 2
_Rendiamola dinamica: abbiamo 20 anni di dati! Quali nazionalità hanno contribuito di più all'immigrazione nel 21° secolo? In quali quartieri l'immigrazione è cresciuta più velocemente? E da quali nazionalità?_

https://colab.research.google.com/drive/19bD95zZ3wbFsmaL5pkFS9RNAYxQw2hh0

Alcuni spunti
1) riclassificazione: sarebbe carino effettuare una ricodifica per aggregare le diverse cittadinanze in macro aree  questo per rendere anche il successivo file shape/jeojson più compatto (e anche per aggregare le cittadinanze con meno frequenze in gruppi omogenei). Qualche idea? (esempio per continente, oppure per indice di sviluppo umano del paese di provenienza )

2) file geojson o shape dei Nil .. dove lo posso trovare?

**Comment by albertocottica** [comment]
Ciao Marco! 

1. Sulla riclassificazione, ci sta lavorando Anna (e tra l'altro abbiamo anche fatto una riflessione, perché il dataset sugli alunni delle primarie ha una disarticolazione diversa da quella usata per il progetto su Bruxelles). Mi pare che avesse quasi finito. Anna non ha ancora un account su GitHub, ma ha promesso che l'avrebbe montato e avrebbe fatto il commit ASAP. 
1. Il file geoJSON/SHP è [qui](http://dati.comune.milano.it/dataset/ds61_infogeo_nil_localizzazione_). Già che ci sei, posso chiederti di metterlo nella cartella Dati del repo?
