### ISSUE TITLE
Produrre i file JSON per le mappe 1, 2 e 3

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/-milano-melting-pot#3]
Per una descrizione delle mappe 1, 2 e 3 vedere [qui](https://github.com/spaghetti-open-data/-milano-melting-pot/wiki/Metodologia-e-workflow). 

* Mappa 1. Il JSON deve avere la seguente struttura: 

      {"Anno": 1999, "Nil": "Duomo", "Cittadinanza": "Cinese, Rep. Popolare", "Maschi": 14,  ù"Femmine": 11,    
      "Totale": 25, "regione": "eastas", "continente": "asia"}

* Mappa 2. Come la mappa 1, ma al posto di Maschi, Femmine e Totale:

      "DMaschi": 14, "DFemmine": 11, "DTotale": 25

D sta per Delta. I campi con D rappresentano l'incremento annuale, in numeri assoluti, del campo senza D. Per esempio

    DMaschi(2010) = Maschi(2010) - Maschi(2009)

L'idea è di rappresentare un incremento con la one person one dot map. In questo caso, però, le persone rappresentate sono sollo quelle di nuovo arrivo, o nuove nate.

* Mappa 3. Come la mappa 1, ma al posto di Maschi-Femmine-Totale abbiano un solo valore, l'indice di segregazione IS:

    "IS": 0.3

**Comment by albertocottica** [comment]
@marco-scarselli il tuo JSON diventa molto grande perché hai tenuto la variabile `Eta`. Quindi contiene un record per le donne egiziane di Bovisa di 0 anni nel 1999, uno per le donne egiziane di Bovisa di 1 anno nel 1999, e così via. Ho fatto [questo](https://github.com/spaghetti-open-data/-milano-melting-pot/blob/master/dati/map1Data.json) che invece somma tutte le donne egiziane: ha un record unico per un genere, nazionalità, quartiere e anno.

**Comment by albertocottica** [comment]
Prodotto anche il JSON per la mappa 2.

**Comment by hal0gen** [comment]
@albertocottica, io ho preso il JSON ultracompatto per la mappa 1 e l'ho modificato per le mappe JS. A me sembra che i dati siano duplicati, è possibile?

**Comment by albertocottica** [comment]
@hal0gen errore cretino mio. Risolto ora.

**Comment by albertocottica** [comment]
Chiudo.
